# configuration

[network]
# Bind to this network address
address = "0.0.0.0"

# Listen on this port
port = 8085

[sources]
# External sources, nostr relay list
relays = [
  "0.0.0.0:8080",
  "0.0.0.0:8080"
]
